services:
  moonpie:
    build: .
    container_name: moonpie
    restart: unless-stopped
    pid: "host"
    network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
